### ISSUE TITLE
【警告】中文网字计划已禁止此网站使用字体！！！

### ISSUE THREAD

**Issue by KonghaYao** [may-today/replay-5525#2]
由于检测到后台流量激增，且并未收到通知，中文网字计划暂时禁止了此网站的使用，以保证字体服务持续运行。
我们的字体 CDN 是公益性质的免费服务，有很多小网站借此能够体验到我们的技术福利，但是过多的流量导致了服务的不稳定，请尽快处理。
您可以独立部署字体，而不是采用我们的 CDN 服务。
采用 cn-font-split 6.0 版本可以将 字体转为 CSS 包，从而像 CDN 一样直接引用，而不需要引用我们的代码。

**Comment by ddiu8081** [comment]
谢谢，已暂时下线引用，正在迁移至独立部署

**Comment by ddiu8081** [comment]
已切换字体包到独立部署，为没有提前预估流量波动致歉。感谢中文网字计划的贡献
